config/routes.rb
Rails.application.routes.draw do
  root "days#index"

  resource :session
  resources :passwords, param: :token
  resources :days do
    post "add_meal", on: :member
    patch "update_meal", on: :member
    delete "delete_meal", on: :member
  end
  resources :meals
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/day.rb
class Day < ApplicationRecord
  has_many :meals, dependent: :destroy
  belongs_to :user

  before_validation :set_nil_goals_to_zero

  private

  def set_nil_goals_to_zero
    self.calorie_goal = 0 if calorie_goal.nil?
    self.protein_goal = 0 if protein_goal.nil?
  end
end

app/controllers/days_controller.rb
class DaysController < ApplicationController
  def index
    @days = Current.user.days.all
  end

  def create
    Day.new(date: Date.today, user_id: Current.user.id).save
    redirect_to days_path
  end

  def show
    @day = Current.user.days.includes(:meals).find(params[:id])

    @total_protein = @day.meals.sum(:protein)
    @total_calories = @day.meals.sum(:calories)
  end

  def update
    @day = Current.user.days.find(params[:id])
    if @day.update(day_params)
      redirect_to day_path
    end
  end

  def destroy
    @day = Current.user.days.find(params[:id])
    @day.destroy

    redirect_to days_path
  end

  def add_meal
    @day = Day.find(params[:id])
    @day.meals.create

    redirect_to day_path
  end

  def update_meal
    @day = Current.user.days.find(params[:id])
    @meal = @day.meals.find(params[:meal][:id])

    if @meal.update(meal_params)
      redirect_to day_path(@day)
    end
  end

  def delete_meal
    @day = Current.user.days.find(params[:id])
    @meal = @day.meals.find(params[:meal_id])

    @meal.destroy

    redirect_to day_path(@day)
  end

  private

  def day_params
    params.require(:day).permit(:calorie_goal, :protein_goal, :date)
  end

  def meal_params
    params.require(:meal).permit(:name, :calories, :protein)
  end
end

app/helpers/days_helper.rb
module DaysHelper
end

app/views/days/_day.html.erb
<%= link_to day_path(day), data: { turbo_frame: "day" } do %>
  <div class="border border-gray-300 rounded-lg p-3 mb-4 cursor-pointer hover:shadow-md transition">
    <p class="font-sans text-xl text-neutral-600"><%= day.date.strftime("%A") %>, <%= day.date %></p>
  </div>
<% end %>

app/views/days/_form.html.erb
<%= form_with(model: day) do |form| %>
  <% if day.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(day.errors.count, "error") %> prohibited this day from being saved:</h2>

      <ul>
        <% day.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :meal_id, style: "display: block" %>
    <%= form.text_field :meal_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/days/_meal.html.erb
<div class="bg-gray-50 p-4 rounded-xl shadow-sm border border-gray-100">
  <%= form_with model: meal, url: update_meal_day_path(day), method: :patch, html: { class: 'space-y-3', novalidate: 'true' } do |form| %>

    <div class="grid grid-cols-3 gap-3">
      <div>
        <label class="block text-xs font-medium text-gray-600 mb-4">Meal Name</label>
        <%= form.text_field :name,
          class: "block w-full border-b border-gray-300 text-base p-2 focus:border-indigo-500 focus:outline-none",
          onchange: "this.form.requestSubmit()",
          value: meal.name %>
      </div>
      <div>
        <label class="block text-xs font-medium text-gray-600 mb-4">Protein (g)</label>
        <%= form.number_field :protein,
          class: "block w-full border-b border-gray-300 text-base p-2 focus:border-indigo-500 focus:outline-none",
          onchange: "this.form.requestSubmit()",
          value: meal.protein,
          step: 10,
          min: 0 %>
      </div>
      <div>
        <label class="block text-xs font-medium text-gray-600 mb-4">Calories (kcal)</label>
        <%= form.number_field :calories,
          class: "block w-full border-b border-gray-300 text-base p-2 focus:border-indigo-500 focus:outline-none",
          onchange: "this.form.requestSubmit()",
          value: meal.calories,
          step: 100,
          min: 0 %>
      </div>
    </div>
    <%= form.hidden_field :id, value: meal.id %>
  <% end %>

  <div class="flex justify-end mt-3">
    <%= button_to "Delete Meal",
      delete_meal_day_path(meal.day, meal_id: meal.id),
      method: :delete,
      class: "text-red-500 cursor-pointer font-medium text-sm" %>
  </div>
</div>

app/views/days/index.html.erb
<% content_for :title, "Days" %>

<div class="h-screen grid grid-cols-5 gap-8 p-6">
  <div class="flex flex-col h-screen overflow-hidden">
    <div class="border-b-indigo-200 border-b-2 pb-2 mb-4">
      <h2 class="font-sans text-4xl font-bold text-indigo-500">Tracked Days</h2>
    </div>
    
    <div class="bg-indigo-500 shadow-md rounded-lg p-3 justify-center mb-4 cursor-pointer flex mr-2"> 
      <%= button_to "+ Add new day", days_path, method: :post, class: "font-sans text-xl font-bold text-gray-100 cursor-pointer"%>
    </div>
    
    <div class="flex-1 min-h-0 overflow-y-auto pr-2">
      <% @days.order(date: :desc).each do |day| %>
        <%= render partial: "day", locals: { day: day } %>
      <% end %>
    </div>
  </div>
  
  <div class="col-span-4 h-full">
    <turbo-frame id="day" class="h-full">
      <div class="flex items-center justify-center h-full">
        No day selected
      </div>
    </turbo-frame>
  </div>
</div>

app/views/days/show.html.erb
<%= turbo_frame_tag "day" do %>
  <div class="space-y-4">
    <div class="flex justify-between items-center border-b-indigo-200 border-b-2 pb-2">
      <h2 class="font-sans text-4xl font-bold text-indigo-500">
        <%= @day.date.strftime("%A") %>, <%= @day.date %>
      </h2>
      <%= button_to "Delete Day", day_path(@day), method: :delete, data: { turbo_frame: "_top" }, 
        class: "bg-red-500 text-gray-50 font-bold py-2 px-4 rounded-lg shadow-md cursor-pointer" %>
    </div>

    <!-- form for daily goals -->
    <%= form_with model: @day, html: { novalidate: true } do |f| %>
      <div class="px-6 py-4 rounded-lg bg-blue-50 shadow-lg border border-blue-100">
        <h3 class="text-2xl font-bold mb-4 text-indigo-500">Daily Goals</h3>
        <div class="flex space-x-4">
          <div class="flex flex-col flex-1">
            <%= f.label :calorie_goal, "Calorie Goal (kcal)", class: "font-medium text-gray-700 mb-2" %>
            <%= f.number_field :calorie_goal,
              step: 100,
              class: "rounded border border-gray-300 p-2 bg-gray-50",
              onchange: "this.form.requestSubmit()" %>
          </div>

          <div class="flex flex-col flex-1">
            <%= f.label :protein_goal, "Protein Goal (g)", class: "font-medium text-gray-700 mb-2" %>
            <%= f.number_field :protein_goal,
              step: 10,
              class: "rounded border border-gray-300 p-2 bg-gray-50",
              onchange: "this.form.requestSubmit()" %>
          </div>
        </div>
      </div>
    <% end %>

    <!-- summary -->
    <div class="p-6 rounded-lg bg-violet-100 border border-violet-200 flex items-center justify-center gap-8 shadow-inner">
      <div class="p-4 bg-gray-50 rounded-lg shadow-inner border-gray-100 flex flex-col items-center">
        <h4 class="font-sans font-bold text-xl text-gray-800">Calories</h4>
        <%= donut_chart(
          { "Calories" => @total_calories, "Remaining" => [@day.calorie_goal - @total_calories, @total_calories <= 0 ? 1 : 0].max },
          {
            height: '200px',
            width: '200px',
            class: 'box',
            options: {
              tooltip: { show: false },
              animation: false,
              color: ['rgb(255, 172, 28)', 'rgb(0, 0, 0, 0.075)'],
              series: {
                labelLine: { show: false },
                label: { show: false },
                emphasis: { disabled: true },
              }
            }
          }
        ) %>
        <p class="font-sans font-medium text-md text-gray-800">
          <%= @total_calories %> / <%= @day.calorie_goal %> kcal
        </p>
      </div>
      <div class="p-4 bg-gray-50 rounded-lg shadow-inner border border-gray-100 flex flex-col items-center">
        <h4 class="font-sans font-bold text-xl text-gray-800">Protein</h4>
        <%= donut_chart(
          { "Protein" => @total_protein, "Remaining" => [@day.protein_goal - @total_protein, @total_protein <= 0 ? 1 : 0].max },
          {
            height: '200px',
            width: '200px',
            class: 'box',
            options: {
              tooltip: { show: false },
              animation: false,
              color: ['rgb(80, 200, 120)', 'rgb(0, 0, 0, 0.075)'],
              series: {
                labelLine: { show: false },
                label: { show: false },
                emphasis: { disabled: true },
              }
            }
          }
        ) %>
        <p class="font-sans font-medium text-md text-gray-800">
          <%= @total_protein %> / <%= @day.protein_goal %> g
        </p>
      </div>
    </div>
    <div class="px-6 py-4 rounded-lg bg-gray-100 shadow-lg border border-gray-200">
      <div class="mb-4 pb-4 border-b border-gray-300 flex justify-between items-center">
        <h3 class="text-2xl font-bold text-gray-800">Meals</h3>
        <%= button_to "+ Add Meal", add_meal_day_path(@day), method: :post, class: "font-sans text-md font-semibold text-gray-100 cursor-pointer px-4 py-2 bg-indigo-500 rounded-lg"%>
      </div>
      <div class="space-y-4">
        <% @day.meals.order(created_at: :desc).each do |meal| %>
          <%= render partial: "meal", locals: { meal: meal, day: @day } %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>